// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' ; 
import 'firebase_options.dart' ; 
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``` 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ76tpyDDZ6mLG4dYfETOD6LMpGO2R9xc',
    appId: '1:833210892294:web:5ce8a54b3fffe926050387',
    messagingSenderId: '833210892294',
    projectId: 'faforever',
    authDomain: 'faforever.firebaseapp.com',
    storageBucket: 'faforever.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3O6xO6SM-fiUD5fzEg3q9cEr_u5sDHLA',
    appId: '1:833210892294:android:74ae271936416626050387',
    messagingSenderId: '833210892294',
    projectId: 'faforever',
    storageBucket: 'faforever.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRUt7WcPx94pP2p6kdGAz53MxTJoYyUQ',
    appId: '1:833210892294:ios:edc0219000a9c20c050387',
    messagingSenderId: '833210892294',
    projectId: 'faforever',
    storageBucket: 'faforever.firebasestorage.app',
    iosBundleId: 'com.example.messapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaRUt7WcPx94pP2p6kdGAz53MxTJoYyUQ',
    appId: '1:833210892294:ios:edc0219000a9c20c050387',
    messagingSenderId: '833210892294',
    projectId: 'faforever',
    storageBucket: 'faforever.firebasestorage.app',
    iosBundleId: 'com.example.messapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ76tpyDDZ6mLG4dYfETOD6LMpGO2R9xc',
    appId: '1:833210892294:web:5ce8a54b3fffe926050387',
    messagingSenderId: '833210892294',
    projectId: 'faforever',
    authDomain: 'faforever.firebaseapp.com',
    storageBucket: 'faforever.firebasestorage.app',
  );

}